
name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull  9441ashiesh/CI-CD:latest
    - name: Delete Old docker container
      run: sudo docker rm -f CI-CD-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container  9441ashiesh/CI-CD
